message_ix/model/MESSAGE/data_load.gms
This PR fixes the issue identified by Pietro Pelizzarui (https://groups.google.com/forum/#!topic/message_ix/E13e_AdhSqY) - there was an overzealous consistency check that the sum of sub-annual time slice duration adds up to 1.
closes #14
=> fix consistency check for subannual timeslices

message_ix/model/version.gms
This PR updates the version number of MESSAGEix to `1.0`. It depends on https://github.com/iiasa/ixmp/pull/38 to update the MESSAGE-scheme specifications and version number hard-coded in the `ixmp.jar`.
=> bump version number of MESSAGEix to 1.0

rmessageix/source/R/init_rmessageix.R, tutorial/Austrian_energy_system/austria_reticulate.ipynb
Fixes #39 change in message_ix model paths redefined considering the new sub-folder message_ix/model
Fixes #31 I only updated the reticulate tutorial because it is the only one using the new message_ix specific classes, form the python code.
=> adapt to changes rmessage_ix and  reticulate tutorial

message_ix/model/MESSAGE-MACRO_run.gms, message_ix/model/MESSAGE_run.gms, message_ix/model/templates/MESSAGE_master_template.gms
I just noticed that we didn't update the reference to the manuscript pre-print in the entrypoint GAMS code files - mea culpa. This PR updates the reference and brings the GAMS code headers in line with the NOTICE.
=> update manuscript reference, etc. in GAMS code

README.md
Just noticed that the readme installations instructions still mention `ixmp` as a submodule. Updated the instructions.
=> removing deprecated "`ixmp` as submodule" from installation instructions

message_ix/core.py
```
```
This PR implements two refactors (arg `mp` instead of  platform, `scenario` instead of `scen`) for the `message_ix.Scenario` constructor in line with recent changes in `ixmp`. It also adds an attribute `is_message_scheme` for a subsequent validation/deprecation warning in `ixmp.Scenario` (see https://github.com/iiasa/ixmp/pull/79).
=> Refactoring Scenario api for consistency with `ixmp.Scenario`

NOTICE.rst, README.md, doc/source/api.rst, doc/source/bibs/main.bib, doc/source/index.rst, doc/source/model.rst, message_ix/model/MESSAGE-MACRO_run.gms, message_ix/model/MESSAGE_run.gms, message_ix/model/templates/MESSAGE_master_template.gms, rmessageix/source/README.md
This PR updates the references in the documentation, notice, etc. to the published version of the MESSAGEix manuscript and to the latest version of the MESSAGEix South Africa manuscript.
The changes are the equivalent updates to https://github.com/iiasa/ixmp/pull/107
=> MESSAGEix manuscript reference update #107

README.md
The readme.md in message_ix points to a http://messageix.iiasa.ac.at/getting_started.html#installation and http://messageix.iiasa.ac.at/getting_started.html#tutorials which do not exist anymore.
=> corrected broken links to installation and tutorials pages on messagix.iiasa.ac.at

RELEASE_NOTES.md, doc/source/api/ixmp.rst, message_ix/core.py, tests/conftest.py, tests/test_core.py
This PR…
- closes #174 by deleting `message_ix.Scenario.clone()`, letting `ixmp.Scenario.clone()` do the work.
- fixes tests broken by [ixmp#130](https://github.com/iiasa/ixmp/pull/130).
- adds tests for cloning of MESSAGEix scenarios.
=> Fix 2-platform cloning & associated tests

message_ix/cli.py, setup.py
This PR changes the setup and model-directory config such that `gdx` files are no longer copied back and forth.
=> no copying gdx files during install and setting of model directory

tutorial/westeros/westeros_baseline.ipynb
The old link does not work any longer (404 error), but 17000 GWh
electricity consumption per year is probably a typo and should be 71000
GWh (in 2016 it rose to 72000 GWh).
(I guess this fix is too small to be mentioned in the release notes.)
=> Fix wrong electricity consumption in tutorial

message_ix/testing.py, tests/test_integration.py
This PR extends the integration tests to prevent the recurrence of the bug detected by @OFR-IIASA where the mapping set `cat_year` was not correctly cloned. The bug itself was fixed in the Java core by https://github.com/iiasa/ixmp/pull/156.
=> add tests that `firstmodelyear` is cloned correctly

INSTALL.rst, tests/test_reporting.py
The url link to download Anaconda seems broken. This change does not require a new patch release and has no change to the code, only docs.
=> Updating the URL to Anaconda in Installation notes

.travis.yml, README.md, appveyor.yml, tutorial/README.rst
This changes the URLs in tutorial/README.rst, so that the built documentation on the `1.2.x` branch will point to the 1.2.0 tutorials.
This change does not require a new patch release (e.g. 1.2.1) because there is not change to code, only docs.
=> Change URLs in tutorial/README.rst to point to 1.2.0 tutorials

message_ix/tools/add_year/README.rst
When trying to run the add_year function from inside a Jupyter notebook I had to import the add_year function from the package first. Adding the import statement explicitly to the README has the benefit of making it easier for less experienced Python users to utilize this function.
=> added import statement for using add_year function in code (vs. via command line)

RELEASE_NOTES.md, message_ix/reporting/__init__.py, message_ix/reporting/pyam.py, tests/test_reporting.py
When `year_time_dim` was a used key somewhere, a call to `as_pyam` from `convert_pyam` was reading in a wrong parameter and spit out an error message.
=> Fix convert_pyam to take care of year_time_dim bug

RELEASE_NOTES.md, doc/source/api.rst, message_ix/core.py, message_ix/testing/__init__.py, message_ix/tools/add_year/cli.py, tests/test_core.py, tutorial/utils/plotting.py, tutorial/utils/run_scenarios.py
Closes #268 and iiasa/ixmp#218.
- Adds test_core.test_year_int for the behaviour described in #268.
- `pytest -k year_int` with only the first commit (b7a8428) should fail.
- Overrides Scenario.equ, .par, .set, and .var to provide the desired behaviour.
- Adjusts other code in `tools.add_year` and tutorials/utils/run_scenarios.py.
See also #254.
=>  Convert 'year'-indexed items to 'int' columns

message_ix/model/MESSAGE/parameter_def.gms
This PR provides alternative representations for the parameter explanations in MESSAGEix documentation. It changes the two tables in Parameters of Technology Section: _Input/output mapping, costs and engineering specifications,_ _Bounds on capacity and activity_. In one version of the tables, the explanatory comments are in the first column and the indices are in the next column. In the other version the order is reversed. The two different versions of the tables are below each other, one will be deleted in the end as we decide which one to keep. The preferred structure can later be implemented to other tables as well. 
Most of the parameters are self-explanatory (e.g. bound_activity_up, construction_time etc.). In those cases the explanatory comments are repetitive and the table might …
=> Addition of parameter definitions in MESSAGEix documentation

ci/conda-requirements.txt
This PR addresses a CI issue encountered in both #276 and #281.
The build log (e.g. [Travis job #1316.2 at L2425](https://travis-ci.org/iiasa/message_ix/jobs/624034624#L2425)) shows:
```
Collecting package metadata (current_repodata.json): done
Solving environment: - 
Warning: 2 possible package resolutions (only showing differing packages):
- defaults::jupyter_console-5.2.0-py36_1, defaults::prompt_toolkit-3.0.2-py_0
- defaults::jupyter_console-6.0.0-py36_0, defaults::prompt_toolkit-2.0.9-py36done
```
and that jupyter_console **5.2.0** and prompt_toolkit **3.0.2** are installed. This leads to the exception:
```
NbConvertApp] Converting notebook /home/travis/build/iiasa/message_ix/tests/../tutorial/Austrian_energy_system/austria.ipynb to notebook
Traceback (most recent call last):
File …
```
=> Specify jupyter_console conda requirement

RELEASE_NOTES.md, message_ix/core.py, message_ix/model/MESSAGE/parameter_def.gms, tests/test_core.py
Closes #278.
Closes #279.
- `Scenario.years_active()` and `.vintage_and_active_years()` are improved.
- `test_years_active()` is rewritten to be more explicit.
- `test_years_active()` was **incorrect**. In this PR, the period '2050' is removed from the expected return value. See the inline comments: https://github.com/iiasa/message_ix/blob/3585ab3eafda1be8d2e24e1fe6190695e07f1410/tests/test_core.py#L222-L228
I have followed our documentation, specifically [here](https://message.iiasa.ac.at/en/stable/model/MESSAGE/sets_maps_def.html#id4) where it reads:
> In MESSAGEix, the key of an element in set year identifies the last year of the period, i.e., in a set year = [2000, 2005, 2010, 2015], the period ‘2010’ comprises the years [2006, .., 2010].
IMO this is more confusing than it needs to …
=> Correct logic of Scenario.years_active()

.gitignore, INSTALL.rst
PR to include `--edtiable` in _MESSAGEix_ docu to be able to run tests. It is present in _ixmp_ docu but **not** in _MESSAGEix_. I discovered after reinstalling MESSAGEix following the docu with the command `pip install .` and then running the tests: `nightly.py` was not skipped and therefore prompting an interruption error.
Also added in `.gitignore.txt` PyCharm's `/.idea` folder (which is automatically created every time you start a project with it).
Should I add sth in `RELEASE_NOTES.md` ? @khaeru
=> Update install from source docs to include pip --editable option

.travis.yml, ci/travis-before_install.sh, ci/travis-install.sh
Around 23 December, the [Travis CRON builds of message_ix](https://travis-ci.org/iiasa/message_ix/builds) began to fail. There seem to be *different* failure modes by OS, as described below. This PR is to debug & fix both.
See e.g. [job #1363.1 @ L383](https://travis-ci.org/iiasa/message_ix/jobs/628779524#L383). Anaconda fails to download packages needed to install, so the build errors:
```
Downloading and Extracting Packages
openssl-1.1.1d       | 2.5 MB    |            |   0% 
wheel-0.33.6         | 42 KB     |            |   0% 
sqlite-3.30.0        | 1.1 MB    |            |   0% 
pip-19.3.1           | 1.6 MB    |            |   0% 
asn1crypto-1.2.0     | 166 KB    |            |   0% 
cryptography-2.8     | 553 KB    |            |   0% 
setuptools-41.4.0    | 510 KB    | …
```
=> Update Travis CI configuration and scripts

RELEASE_NOTES.md, setup.py, tests/test_feature_price_emission.py, tests/test_reporting.py, tests/test_tutorials.py, tutorial/utils/plotting.py
Closes #177 by removing remaining Python 2 compatibility code.
See also iiasa/ixmp#239.
=> Drop support for Python 2

message_ix/core.py, tests/test_core.py
This PR closes #293.
Added a test to check if the error found in #293 is solved.
Basically, the _JDBCBackend_ does not have an attribute called `get_cat_list`. The Backend method is named `cat_list` instead:
[](https://github.com/iiasa/ixmp/blob/39e900dea02950bcea69e273e79002b5748551b4/ixmp/backend/base.py#L715-L717)
[](https://github.com/iiasa/ixmp/blob/39e900dea02950bcea69e273e79002b5748551b4/ixmp/backend/jdbc.py#L674-L675)
This problem can ideally be solved by somebody with experience in _JDBCBackend_.
=> Add test for cat_list()

INSTALL.rst
This adds a note about the need to add JAVA_HOME to the environment variables when JVM is not found. 
Since multiple (new) users got stuck when first running MESSAGE_ix (see issue #35 ), a note with one example linking instructions on how to properly set the JAVA_HOME variable are added to the installation instructions.
=> Add JAVA_HOME env variable construction to installation page

RELEASE_NOTES.rst, ci/pip-requirements.txt, message_ix/cli.py, tests/test_cli.py, tests/test_core.py, tutorial/utils/run_scenarios.py
Related to iiasa/ixmp#254, this PR removes usage of ixmp features that were marked as deprecated in ixmp 2.0. There were no marked deprecations in message_ix 2.0 itself.
Run your own code(s) against this branch to ensure they still work; or make any necessary adjustments.
=> Adjust to v2.0 deprecations in ixmp

ci/appveyor-install.ps1, ci/travis-install.sh, message_ix/testing/nightly.py, setup.cfg, tests/test_integration.py, tests/test_nightly.py, tests/test_utils.py
Update `message_ix.testing.nightly` and the nightly tests to use the `path=` rather than `dbprops=` argument for the path to a HyperSQL JDBC database. Since the old, deprecated argument was removed by iiasa/ixmp#254, this is necessary for the Travis nightly/cron CI checks to pass.
Other changes
- Adjust imports of pandas.util.testing to pandas.testing; the former is deprecated.
- Adjust CI scripts to align better between AppVeyor/Travis, and with ixmp.
- Copy a fix from iiasa/ixmp#247 to avoid noise in CI logs from the pytest `faulthandler` plugin.
1. Confirm that the nightly tests run and pass for this branch.
2. Revert the changes to `pytestmark` in test_nightly.py.
=> Update Platform semantics in nightly tests

message_ix/models.py
iiasa/ixmp#212 adds a feature to the `ixmp.model.GAMSModel` class, allowing a temporary directory for input and output GDX files, listing files, etc.
This feature is used for e.g. ixmp's DantzigModel; but it is _not_ desired for MESSAGE models, where the user may want to inspect the GDX files. This PR explicitly disables the feature for MESSAGE, MESSAGE_MACRO, etc.
- Confirm CI passes.
- Confirm MESSAGE models can be run with this branch and the branch in iiasa/ixmp#212 (fyi @behnam-zakeri)
=> Adjust models.MESSAGE for iiasa/ixmp#212

ci/pip-requirements.txt
Adjust CI configuration for AppVeyor and Travis so that the message_ix `2.0.x` branch builds using the ixmp `2.0.x` branch.
This avoids failing builds caused by API changes on ixmp `master` towards ixmp `3.x`. There is no plan to make ixmp `3.x` compatible with message_ix `2.x`.
Ensure that CI checks pass.
=> Track ixmp 2.0.x branch for CI of message_ix 2.0.x

RELEASE_NOTES.rst, message_ix/reporting/__init__.py, message_ix/reporting/pyam.py, message_ix/testing/__init__.py, message_ix/tests/test_integration.py, message_ix/tests/test_reporting.py
Adds two features needed for the MESSAGEix-GLOBIOM reporting (in `message_data`) to `reporting.computations.as_pyam()` and `Reporter.convert_pyam()`:
- *units* argument, specifying the desired units in the resulting pyam.IamDataFrame.
- *replace_vars* argument. This specifies the name of a different key—e.g. `'activity variables'` in the tests—that produces a dict with name mappings. Entries in the 'Variable' column are replaced according to this dict.
Confirm that CI passes.
=> Specify units, replace variable names in Reporter.convert_pyam

RELEASE_NOTES.rst, doc/source/api.rst, message_ix/core.py, message_ix/tests/test_core.py
This PR removes the `message_ix.Scenario.to_excel()` and `.read_excel()` methods. ~iiasa/ixmp#286~ iiasa/ixmp#289 adds these to `ixmp.Scenario`, so they are available for non-MESSAGE scenarios.
It also incorporates test improvements from #265.
- ~Wait for iiasa/ixmp#289 to merge, or check out its branch.~
- Run tests against the updated ixmp code.
- Try with any old Excel exports one has lying around.
=> Transfer Excel data I/O to ixmp

RELEASE_NOTES.rst, doc/source/reporting.rst, message_ix/reporting/__init__.py, message_ix/reporting/computations.py, message_ix/reporting/pyam.py, message_ix/tests/test_reporting.py, message_ix/tests/test_tutorials.py
- `Reporter.convert_pyam()`
- The argument *year_time_dim* is passed as a keyword argument. If passed as a string positional argument ('y'), the Reporter internally interpreted it as a reference to the key, 'y', that yields the list of years. This list is supplied to `as_pyam()`, which is expecting just the string 'y'.
- Avoid manipulating units if the pd.DataFrame is empty.
- Add auto-reported `price emission` quantity = `PRICE_EMISSION` broadcast across
- `computations.map_as_qty` now automatically adds a map from 'all' to all elements in the target set, e.g. of all technologies, `t`. This exists in GDX and Java but isn't returned by the standard methods, for some reason.
- Note that CI checks pass.
=> Add reporting improvements from the 2020 hackathon

RELEASE_NOTES.rst, doc/source/api.rst, message_ix/models.py
Closes #222.
- Re-run any multi-process parallel run code that triggered the original issue; confirm it does not recur.
- Confirm that CI checks pass.
=> Only unlink GAMS CPLEX options file if it exists

ci/codecov.yml, message_ix/tests/test_integration.py, tutorial/westeros/westeros_report.ipynb
- `westeros_report` tutorial is adjusted to assign its Platform() instance to a variable; this prevents it from being cleaned up prematurely by ixmp.
- Also un-xfail some tests that have been fixed.
=> Adjust to iiasa/ixmp#298

ci/conda-requirements.txt, ci/pip-requirements.txt
Related to iiasa/ixmp#279
- Confirm that CI checks pass.
=> Bump CI requirement for JPype to 0.7.5

message_ix/cli.py
Added _Docstring_ for the `message-ix dl` command is appropriate, before it was missing.
Notes: **second tentative**, since in https://github.com/iiasa/message_ix/pull/353 I forced-pushed the revert of the only commit in that PR so Git automatically closed it.
=> Update doctring message-ix-dl

.github/workflows/anaconda.yml, .github/workflows/conda.yml, .github/workflows/miniconda.yml, .github/workflows/pytest.yml, CONTRIBUTING.rst, INSTALL.rst
- Add two GitHub Actions workflows to check that installation from conda-forge, *exactly* per the instructions in the documentation, succeeds, using both Miniconda and Anaconda.
- Update the install instructions to explain and guide around the fact that identical `conda` commands produce different results on Anaconda and Miniconda; see conda-forge/cf-mark-broken#78 for details.
See also: https://github.com/iiasa/message_ix/issues/349#issuecomment-642240665.
Confirm that CI checks pass.
=> Add GitHub Actions workflow to check conda install

doc/source/conf.py, doc/source/reporting.rst, message_ix/reporting/computations.py, message_ix/tests/test_reporting.py, tutorial/westeros/westeros_report.ipynb
iiasa/ixmp#317 cleans up the reporting.Quantity semantics/API so that they are completely agnostic with respect to the internal data format. That's to make it easier to later swap `ixmp.reporting.attrseries` (a wrapped pd.Series) for `ixmp.reporting.sparsedataarray` (an xr.DataArray with pydata/sparse storage).
This PR adjusts `message_ix.reporting` to avoid calling pd.Series-specific methods, and instead use the general Quantity API.
- First, merge iiasa/ixmp#317.
- Confirm CI checks pass.
=> Adjust to ixmp#317

README.md, RELEASE_NOTES.rst, rmessageix/DESCRIPTION, tutorial/Austrian_energy_system/austria.ipynb, tutorial/westeros/westeros_baseline.ipynb, tutorial/westeros/westeros_flexible_generation.ipynb, tutorial/westeros/westeros_report.ipynb
As noted by @OFR-IIASA, some links to the RTD documentation had not been updated to the current domain `docs.messageix.org`. I searched/replaced all occurrences throughout the codebase.
Parallel to iiasa/ixmp#356.
Check that the docs link in the README file on this PR branch (i.e. https://github.com/iiasa/message_ix/tree/85374675e3f7db4ffde7b8984aca9f16e491261d) works.
- ~Add or expand tests.~ N/A, docs only
=> Update domain for RTD docs in README, release notes, and tutorials

RELEASE_NOTES.rst, message_ix/model/MESSAGE/model_core.gms
Updating the documentation of the MESSAGE objective function  to match the objective function.
Changing from the discountfactor *df-year* to *df-period* in the documentation of the MESSAGE objective function  to match the objective function.
Confirm that using df-period rather than df-year in the objective function is intended.
- ~Add or expand tests.~ No change in behaviour, simply refactoring.
=> cleanup inconsistency between in gams documentation and equation (OBJ)

.github/workflows/pytest.yml, RELEASE_NOTES.rst, message_ix/core.py, message_ix/tests/test_core.py
Addresses two CI issues:
- Codecov is not correctly attaching status checks to message_ix PRs after GitHub Actions workflow runs.
- This is in contrast to ixmp, which works.
- The Codecov action used in the workflow seems to have some limitations, see e.g. https://github.com/codecov/codecov-action/issues/51#issuecomment-595077546. This might be related because, unlike ixmp, the message_ix GHA configuration checks the repo out into a subdirectory.
- Replaced with step that manually downloads and runs the codecov script.
- See codecov/codecov-action#110—once this is accepted/merged, we can return to using the action.
- The same issue as iiasa/ixmp#359: the checks for Python 3.6 were actually being run with Python 3.8. This allowed #286 to pass and be merged, even though it contained syntax …
=> Fix Codecov status checks and Python 3.6 build

RELEASE_NOTES.rst, message_ix/reporting/pyam.py, message_ix/testing/__init__.py, message_ix/tests/test_core.py, message_ix/tests/test_reporting.py, message_ix/tools/add_year/README.rst, message_ix/utils.py, tutorial/Austrian_energy_system/austria.ipynb, tutorial/westeros/westeros_baseline.ipynb
During work on iiasa/message_ix#120, @francescolovat and I discovered that `reporting.pyam.concat()` did not chain correctly to `ixmp.reporting.computations.concat()` in cases where the objects concatenated were **not** pyam.IamDataFrames.
This PR fixes this issue and adds a test.
Note that the CI checks all pass.
- ~Add, expand, or update documentation.~ Fix to intended behaviour.
=> Fix passthrough of reporting.pyam.concat() args

.github/workflows/lint.yml, .github/workflows/nightly.yml, .github/workflows/pytest.yml, NOTICE.rst, README.md, RELEASE_NOTES.rst, doc/conf.py, doc/contrib/cla.rst, doc/contrib/release.rst, doc/contrib/tutorial.rst, doc/contrib/version.rst, doc/contributing.rst, doc/index.rst, message_ix/model/MESSAGE-MACRO_run.gms, message_ix/model/MESSAGE_run.gms, rmessageix/DESCRIPTION, setup.cfg, tutorial/README.rst, tutorial/westeros/westeros_report.ipynb
- Update copyright year and program name
- Adjust for mypy
=> Prepare v3.2.0 release

.github/workflows/lint.yml, .github/workflows/nightly.yml, .github/workflows/pytest.yml, .readthedocs.yml, ci/rtd-requirements.txt, conftest.py, message_ix/__init__.py, message_ix/testing/__init__.py, message_ix/tests/conftest.py, message_ix/tests/test_feature_bound_activity_shares.py, message_ix/tests/test_feature_price_commodity.py, message_ix/tests/test_feature_price_emission.py, message_ix/tests/test_integration.py, message_ix/tests/test_macro.py, message_ix/tests/test_reporting.py, message_ix/tests/test_testing.py, message_ix/tests/test_util.py
Other changes:
- Use more readable, upper-case display names for GitHub Actions workflows.
- Give the pytest `-rA` option to show verbose output for even passing tests.
- Move pytest hooks to the top-level conftest.py from the one in the tests/ directory; they are not picked up/run in the latter location.
- `ixmp.ModelError` (iiasa/ixmp#398) is now importable from the top level of `message_ix`; check for this in tests instead of `CalledProcessError`
- Use the `solve(quiet=True)` option added by iiasa/ixmp#399 throughout the test suite.
Ensure that RTD builds complete successfully.
- ~Add, expand, or update documentation.~ N/A, CI only
- ~Update release notes.~ N/A, CI only
=> Install ixmp from GitHub master on RTD

.github/workflows/nightly.yml, .github/workflows/pytest.yml, ci/nightly.yaml, message_ix/testing/nightly.py, message_ix/tests/reporting/test_computations.py, message_ix/tests/test_core.py, message_ix/tests/test_feature_addon.py, message_ix/tests/test_feature_bound_activity_shares.py, message_ix/tests/test_feature_bound_emission.py, message_ix/tests/test_feature_price_commodity.py, message_ix/tests/test_feature_price_emission.py, message_ix/tests/test_feature_storage.py, message_ix/tests/test_macro.py, message_ix/tests/tools/test_add_year.py, message_ix/tests/util/test_tutorial.py, message_ix/tools/add_year/__init__.py
This PR uses the new [`iiasa/actions`](https://github.com/iiasa/actions) repo and `setup-gams` action to install GAMS on GitHub Actions runners.
This approach is more modular and simple than the prior approach of checking out the ixmp repo and calling a script contained there.
Other changes:
- Also use the [`ts-graphviz/setup-graphviz`](https://github.com/marketplace/actions/setup-graphviz) action, which does essentially the same thing as the Bash script used from ixmp
- Remove code in `message_ix.testing.nightly` that handles the GAMS license upload and download. The new action uses license file contents stored as a [repository secret](https://docs.github.com/en/actions/reference/encrypted-secrets#using-encrypted-secrets-in-a-workflow).
No review; CI changes only.
- ~Add, expand, or …
=> Install GAMS using iiasa/actions for CI

RELEASE_NOTES.rst, message_ix/core.py, message_ix/tests/test_core.py
This PR ensures that the years_active() function retrieves the lifetime that corresponds to the vintage for which the active years are being retrieved, and not the first in the list.
- Ensure the new tests work.
=> Fix bug in years_active() function

.gitattributes, .github/workflows/pytest.yaml, doc/rmessageix.rst, message_ix/tests/test_tutorials.py
This copies an approach used in xarray: https://github.com/pydata/xarray/blob/master/.gitattributes
- We often need to rebase branches to resolve merge conflicts in the release notes. Sometimes this is the *only* conflict.
- This attribute causes git to use a different merge strategy, for this file only: including lines from both branches.
- This will usually have the intended effect. The order of the lines may be unpredictable, but the order is not super important.
No review; CI changes only.
- ~Add, expand, or update documentation.~ N/A; CI changes only.
=> Set .gitattributes for RELEASE_NOTES.rst

.github/workflows/lint.yaml
As part of #327, the mypy step of the lint workflow began to fail.
This is because mypy 0.900 et seq. were released; in these versions (unlike mypy 0.8xx), type stubs for 3rd-party packages are not bundled and must be installed separately.
This PR adds these to lint.yaml:
- types-requests
- types-PyYAML
- types-pkg_resources
No review/FYI only: changes to CI.
- ~Add, expand, or update documentation.~ N/A, CI only
=> Install 3rd party type stubs for mypy

.gitignore, RELEASE_NOTES.rst, message_ix/reporting/computations.py, message_ix/tests/test_reporting.py, tutorial/westeros/westeros_report.ipynb
- As detected in #491:
- Improve performance of generating the full-scale MESSAGEix reporting graph.
This was a performance regression introduced in genno 1.5.x (khaeru/genno#42); now fixed by khaeru/genno#47 / version 1.6.0, and it cause some tutorial notebooks to exceed the timeout limit of 10 seconds per cell.
- Use `in rep` not `in rep.graph` for more flexible `genno.Computer.__contains__()`.
- Adjust to pyam 1.0.
In particular, IamDataFrame.line_plot() was marked deprecated in 0.10 (IAMconsortium/pyam#473) and then removed as of 1.0, without an intervening major release. This broke the westeros_report.ipynb tutorial.
No review: internal/test suite only.
=> Adjust for genno 1.6, pyam 1.0

RELEASE_NOTES.rst, message_ix/core.py, message_ix/tests/test_core.py
This PR ensures that the function`years_active()` uses sorted results from the parameter `duration_period`.
The observed issue of `years_active()` returning incorrect results as described in #485 is herewith resolved.
=> Ensure `years_active()` uses sorted results

doc/conf.py, doc/contributing.rst, message_ix/core.py
This PR adjusts to avoid use of `ixmp.utils.isscalar`, deprecated in iiasa/ixmp#422.
- View the diff
- ~Add, expand, or update documentation.~ N/A; internals, no user-facing change.
- ~Update release notes.~ N/A
=> Use np.isscalar; improve contributing.rst

.github/workflows/nightly.yaml, message_ix/tests/data/scenarios.yaml
This PR adjusts the expected objectives of both scenarios in the `scenario.yaml` file. This is needed due to the adjustment of the soft constraint of `new capacity` and `activity` by merging the PR #474. 
=> Adjust objective values for nightly test scenarios

RELEASE_NOTES.rst, message_ix/tests/test_reporting.py
This PR adjusts the test suite of `message_ix/tests/test_reporting.py::test_reporter_from_westeros` for compatibility with pyam v1.1.0. 
Merging this PR should close the issue #498. 
=> Adjust test suite for pyam v1.1.0 compatibility

.github/workflows/conda.yaml, INSTALL.rst
This PR updates the installation documentation using Anaconda with an additional step to set the channel priority to strict with ` $ conda config --set channel_priority strict`. This lead to errors in the past and was issued in #480. Merging this PR will close this issue.
- Build the documentation and look at the installation page.
=> Update installation documentation using Anaconda

message_ix/tests/test_tutorials.py
This PR marks test _message_ix/tests/test_tutorials.py::test_tutorial[R_austria]_ as xfail due to flakiness. Merging this PR will close issue #507. 
=> Mark R_austria tutorial test as xfail on macos-latest-py3.8

RELEASE_NOTES.rst, doc/time.rst, message_ix/model/MESSAGE/data_load.gms, message_ix/tests/test_feature_duration_time.py
This PR changes the way the GAMS formulation checks the sum of `duration_time` of sub-annual time slices (hereafter "time slices"). At the moment, GAMS checks that the sum of `duration_time` at a temporal level is equal to 1. However, as the precision differs between GAMS and python values, in some cases a very small, negligible difference in the scale of 1e-12 triggers an error.  This PR changes the way this check, is done in GAMS, i.e., from equality to 1 to check if the difference is smaller than 1e-12.
For testing this PR a model with time slices should be used, preferably with many time slices with different `duration_time`. The review can use the tests designed in this PR, change the number of time slices per year and see if the check for the sum of `duration_time` in GAMS works.
=> Change precision of GAMS check for parameter "duration_time"

.github/workflows/conda.yaml, message_ix/tests/test_tutorials.py
This PR addresses the CI failures in the "Install form conda-forge" workflow. Closes #518. 
For this, a new generated GitHub Action _setup-conda_ is used, https://github.com/iiasa/actions/pull/2.
By now the workflow on windows-latest succseeds due to the following adjustments:
1. Use version Anaconda version 2019.03 as mentioned [here](https://github.com/iiasa/actions/tree/main/setup-conda).
2. For now, specify the root directory with `--rootdir=D:\a\_actions\iiasa\actions\main\setup-conda\${{ matrix.conda }}3\envs\testenv\lib\site-packages` when running `pytest` (might not be the best solution though). This adjustment is needed since `platform_name` is build by the `nodeid`, which ["...is rooted at the rootdir..."](https://docs.pytest.org/en/latest/reference/customize.html#initialization- …
=> Address CI failures in the workflow "Install from conda-forge"

setup.cfg
This PR removes `genno[plotnine]` from the setup.cfg since it is, when merging  https://github.com/iiasa/ixmp/pull/431 (and releasing `ixmp`), implied by `ixmp[report]` and therefore by `%(report)s`. See ToDo in `message_ix` [here](https://github.com/iiasa/message_ix/blob/main/setup.cfg#L58).
<!--
=> Remove extras_require genno[plotnine]

RELEASE_NOTES.rst, doc/time.rst, message_ix/model/MESSAGE/data_load.gms, message_ix/model/MESSAGE/model_core.gms, message_ix/model/MESSAGE/sets_maps_def.gms, message_ix/model/includes/period_parameter_assignment.gms, message_ix/models.py, message_ix/tests/test_feature_temporal_level.py, message_ix/tests/test_reporting.py, message_ix/tests/test_tutorials.py
This PR aims to improve the representation of sub-annual time slices, hereafter simply "time slices", in the GAMS code, and remove inconsistencies across the formulation in relation to the relative duration of time slices represented as `duration_time_rel`. This enhancement will resolve the bug reported in [#Issue 363](https://github.com/iiasa/message_ix/issues/363) and [#371](https://github.com/iiasa/message_ix/issues/371) , and the tests designed in this PR will check the issues discussed in [#Issue 193](https://github.com/iiasa/message_ix/issues/193). More details as follows:
**Background:**
The existing GAMS formulation uses `duration_time_rel` when evaluating _values_ in different MESSAGEix parameters for the index of `time` based on the duration of that time slice relative to the …
=> Enhance mathematical formulation to treat sub-annual time slices consistently

.github/workflows/conda.yaml
This PR solves the failing "Install from conda-forge" workflow.
Further discussion and insights related to this PR/issue can be found in the [MESSAGEix slack channel thread](https://iiasa-ece.slack.com/archives/CD0GBHHA4/p1642694884041600 ).
Closes issue #540. 
=> Address failing "Install from conda-forge" workflow

message_ix/model/MESSAGE/sets_maps_def.gms
This PR adjusts the declaration of `time_relative(time)` by deleting "=" to address failing tests / scenario runs with GAMS version 24.9.1.
Closes https://github.com/iiasa/message_ix/issues/546.
- Run a scenario via CLI / run pytest locally with GAMS version 24.9.1
=> Adjust declaration of time_relative(time)

.github/workflows/lint.yaml, .github/workflows/nightly.yaml, .github/workflows/publish.yaml, .github/workflows/pytest.yaml, RELEASE_NOTES.rst, doc/api.rst, doc/time.rst, message_ix/__init__.py, message_ix/models.py, message_ix/tests/test_tutorials.py, setup.cfg
This file adds a new recognized key, `"message model options"`, in the user configuration file (~/.local/share/ixmp/config.json or similar), that corresponds to passing options to `Scenario.solve(…)` ([docs](https://docs.messageix.org/en/stable/api.html#message_ix.Scenario.solve)).
So, for instance, with the following in config.json:
```json
{
"my-platform": {"backend": "jdbc", "etc": "etc"},
"...": "...",
"message solve options": {"lpmethod": 4},
}
```
…then:
```py
s.solve()
```
is updated to have the same effect as:
```py
s.solve(solve_options={"lpmethod": 4})
```
Also:
- #532
- iiasa/ixmp#415 fixed the issue underlying “message model dir” not working as described here.
=> Read GAMS CPLEX solver options for MESSAGE from user config

RELEASE_NOTES.rst, message_ix/reporting/__init__.py
This PR splits the part of Reporter.from_scenario() that populates the graph with tasks for MESSAGE-specific reporting calculations.
This change makes it possible to add/use these tasks via a Reporter _without_ any underlying Scenario object, e.g. with simulated model output data for quantities like `CAP:nl-t-ya` instead of operations that read these values from a Scenario.
In support of iiasa/message_data#296.
=> Add Reporter.add_tasks()

INSTALL.rst
This PR documents the approximately installation time with conda due to #558.
Closes #562 
- Build the documentation and look at the installation page using Anaconda at "Step 8".
Estimated time <2 min.
=> Document approx. installation time with conda

message_ix/cli.py, message_ix/tests/test_cli.py
This PR adjusts the CLI `message-ix copy-model` function. 
Closes #560. 
- Run `message-ix copy-model --set-default "PATH"` to check if CLI works.
Estimated time: < 3 minutes
=> Address failing copying of GAMS files

RELEASE_NOTES.rst, message_ix/model/MESSAGE/model_core.gms
There is a typo in GAMS equations specified in issue #521, which is corrected through this PR. The inline documentation is already correct and does not need any change. This PR does not need any additional test.
**Required:** 
Please look at equation `RENEWABLES_EQUIVALENCE` in `model_core.gms`. Parameter `input` is indexed with `time_act` and `time`, multiplied by variable `ACT` which is indexed by `time`. Here, the correct index of time for ` ACT` must be `time_act`. To check this, one needs to know if the order of indexes of `time_act` and `time` in parameter `input` is correct or not. This can be checked, for example, by running a command `scenario.idx_names("input")`.
=> Correct index of "time" in equation RENEWABLES_EQUIVALENCE

RELEASE_NOTES.rst, message_ix/model/MESSAGE/data_load.gms, message_ix/model/MESSAGE/sets_maps_def.gms, message_ix/models.py, message_ix/testing/__init__.py, message_ix/tests/test_feature_capacity_factor.py, message_ix/tests/test_feature_temporal_level.py, message_ix/tests/test_reporting.py, message_ix/tests/test_tutorials.py
This PR adds tests for parameter "capacity_factor" to address the requirements mentioned in #515.
Please make a copy of this branch, run the test with the existing code, and the tests should pass.
=> Resolve the issue of zero capacity factor

.github/pull_request_template.md, .github/workflows/conda.yaml, INSTALL.rst
Since https://github.com/conda-forge/admin-requests/pull/385 got merged the latest version of `message-ix` gets again installed via `conda install message-ix`.
This PR 
- adjusts the documentation for the steps to install  `message-ix` via Anaconda and
- un-pins the `message-ix` version in the conda CI workflow.
Closes https://github.com/iiasa/message_ix/issues/558.
FYI: Locally the time to solve the environment takes now around ~7 minutes.
Note the CI checks all pass.
=> Un-pin message-ix version in Documentation and Conda CI workflow

RELEASE_NOTES.rst, message_ix/model/MESSAGE/model_core.gms
This PR extends the documentation of the decision variables `CAP` and `CAP_NEW`.
Closes #48. 
- Build the documentation and look at "MESSAGE core formulation" > "Variable definitions" > "Decision variables".
=> Extend documentation of `CAP` and `CAP_NEW`

RELEASE_NOTES.rst, message_ix/model/MESSAGE/parameter_def.gms
This PR extends the documentation on historical capacity and activity values.
Closes #496 
- Build the documentation and look at the parameter definitions "Historical capacity and activity values"
=> Extend documentation on historical capacity and activity values

.github/workflows/pytest.yaml, .gitignore, RELEASE_NOTES.rst, doc/api.rst, message_ix/core.py, message_ix/tests/test_core.py, message_ix/tests/test_feature_vintage_and_active_years.py
This PR extends the features of the function `vintage_and_active_years()` based on issue #571 
- Build the documentation and look at a description of `vintage_and_active_years()`
- Ensure that changes/additions are self-documenting, i.e. that another
developer (someone like the reviewer) will be able to understand what the code
does in the future.
=> Extend feature vintage_and_active_years()

.github/workflows/lint.yaml, .github/workflows/nightly.yaml, message_ix/models.py, pyproject.toml
Closes #591 by ensuring that the MESSAGE.enforce() method, ensuring consistency of internal sets and parameters, is called when a scenario is solved using the MESSAGE_MACRO class.
Note that this demonstrates the workflow described at https://github.com/iiasa/message_ix/pull/603#issuecomment-1123486549:
> 1. Author opens a PR with some commits. Status in our tracker is "In progress".
> 2. Identifying that their PR ~touches the GAMS implementation~ involves the nightly tests, author pushes a commit uncommenting these lines: https://github.com/iiasa/message_ix/blob/b572ccee45c293a88f1f2acf91a0811d50cf6593/.github/workflows/nightly.yaml#L6-L8 with a message like `TEMPORARY Enable nightly workflow for PR.`
> 3. Author develops their PR, pushing commits, noting and ensuring that the "pytest", …
=> Ensure MESSAGE.enforce() runs for MESSAGE_MACRO

.github/workflows/lint.yaml, .gitignore, message_ix/tests/test_feature_vintage_and_active_years.py
In #451 and https://github.com/iiasa/message_ix/pull/623#issuecomment-1154924231 we discovered that with newer numpy (1.22, 1.23) type errors ocurred in `.tests.test_feature_vintage_and_active_years`. This PR:
- Addresses the new type error.
- Sets the "lint" CI workflow to run nightly, so that these are picked up by the scheduled job rather that during devs' unrelated PRs.
- ~Add, expand, or update documentation.~ N/A, linting only, no change in behaviour
=> Satisfy mypy under numpy >= 1.22

RELEASE_NOTES.rst, message_ix/core.py
This PR introduces the updated syntax to resolve the issue as described in Issue #618 
Check code adjustments and ensure all tests pass.
- ~Add, expand, or update documentation.~ N/A, syntax correction, no change in behavior
=> Tolerate non-default pandas Index in `Scenario.years_active()`

RELEASE_NOTES.rst, doc/reporting.rst, message_ix/reporting/__init__.py, message_ix/reporting/computations.py, message_ix/tests/reporting/test_computations.py, message_ix/tests/test_reporting.py, pyproject.toml, tutorial/westeros/westeros_report.ipynb
This allows simple, 1-step conversion of `genno.Quantity()` into a pd.DataFrame suitable for `Scenario.add_par()` or `ixmp.reporting.computations.update_scenario`.
Also closes #239 and adds improvements from the June 2022 workshop.
- Read the documentation of the new computation; ensure it is clear.
- See e.g. https://github.com/iiasa/message_data/blob/601df5c74a55054782ed4ccf1d6f6d2bddaa92b6/message_data/model/transport/demand.py#L351-L358 for a usage of the new function to convert a genno.Quantity `fv:n-y` to the MESSAGE `demand` parameter, mapping some dimensions and filling others.
- Confirm the CI checks all pass.
=> Add `as_message_df()` reporting computation

RELEASE_NOTES.rst, doc/reporting.rst, message_ix/reporting/__init__.py, message_ix/tests/test_reporting.py, message_ix/tests/test_tutorials.py
This change was missed in #628, which adjusted the keys of other reports.
- Read the diff and note that CI checks all pass.
=> Adjust default reporting key to "message::default", following genno

RELEASE_NOTES.rst, doc/macro.rst, message_ix/model/MESSAGE-MACRO_run.gms, message_ix/models.py
This PR adds an additional check to detect the oscillation between the various iterations when running MESSAGE-MACRO.
The additional check looks to see if the objective function bounces between two points.
Some of the findings and solutions to handling unscaled infeasibilities discussed in issue #337 have also been updated.
Review code updates to "MESSAGE-MACRO_run.gms".
Review updated documentation to the section "calibrate-and-tune-message-macro" found in "marco.rst".
~- [ ] Add or expand tests; coverage checks both ✅~ N/A as this cannot be tested
=> Add additional oscillation indicator

.github/workflows/conda.yaml, .github/workflows/lint.yaml, .github/workflows/nightly.yaml, .github/workflows/publish.yaml, .github/workflows/pytest.yaml, RELEASE_NOTES.rst, pyproject.toml
This works around CI failures observed here due to has2k1/plotnine#619, which affects message_ix via khaeru/genno#71. For the moment, matplotlib v3.6.0 cannot be used with genno and thus with message_ix.reporting.
Also:
- Upgrade versions of actions used in CI workflows.
- Standardize the method for querying pip's cache.
- Clean up incomplete edits to release notes in #645.
- ~Add, expand, or update documentation.~ N/A
=> Work around CI failure due to plotnine

.github/workflows/nightly.yaml, .github/workflows/pytest.yaml
After #649, the "nightly" workflow fails, likely due to actions/setup-python@v4 no longer automatically defaulting to the latest version. Fix.
- ~Add, expand, or update documentation.~ N/A, CI changes only
=> Specify Python version for "nightly" CI workflow

RELEASE_NOTES.rst, doc/api.rst, doc/conf.py, doc/contrib/tutorial.rst, doc/contrib/version.rst, message_ix/core.py, message_ix/macro.py, message_ix/model/MESSAGE/parameter_def.gms, message_ix/models.py
With pandas 1.5.0, the test `message_ix/tests/test_macro.py::test_multiregion_derive_data` began to fail, e.g. [here](https://github.com/iiasa/message_ix/actions/runs/3087665121/jobs/4993267658#step:16:185).
This PR adjusts the function to work with both pandas 1.4.4 and 1.5.0.
- Look at the change to the method mentioned in the PR title.
- Run `pytest -k macro` using both pandas 1.5.0 and pandas < 1.5.0.
- Confirm the tests pass under both conditions.
=> Adjust `.macro.Calculate._bconst` for pandas 1.5.0

message_ix/tests/conftest.py
The release of pint 0.20 triggered test failures. Some of these were fixed upstream (IAMconsortium/units#40, khaeru/genno#74); this PR takes care of those in `message_ix` itself.
- ~Add, expand, or update documentation.~ N/A, test suite changes only.
=> Adjust "ureg" test fixture for pint 0.20

.github/workflows/lint.yaml, .github/workflows/nightly.yaml, .github/workflows/publish.yaml, .github/workflows/pytest.yaml
Until numba/numba#8304 is closed by a release that supports Python 3.11, Python 3.10 is the latest we can test/support. This resolves failures of the "nightly" CI workflow, e.g. [here](https://github.com/iiasa/message_ix/actions/runs/3391374683).
Also:
- Use the built-in feature of the first-party actions/setup-python to cache pip packages. The manual usage of actions/cache and related state variables is no longer needed for these.
- ~Add, expand, or update documentation.~ N/A; CI changes only
=> Exclude Python 3.11 from CI

RELEASE_NOTES.rst, message_ix/model/MESSAGE/model_core.gms, message_ix/testing/__init__.py, message_ix/tests/test_equation_NEW_CAPACITY_CONTRAINT.py
This PR addresses an issue which occurs when calculating the upper and lower constraints for new capacity (`NEW_CAPACITY_CONSTRAINT_LO` and `NEW_CAPACITY_CONSTRAINT_UP`).
The issue resulting from the current formulation will vary the magnitude of the bound when the `duration_period` of the time-period for the bound is being calculated, differs to the previous time-period.
An adjustment of the bound is made to take into consideration the change in the `duration_period`.
=> Correct calculation of NEW_CAPACITY_CONSTRAINTs

RELEASE_NOTES.rst, doc/macro.rst, message_ix/model/MESSAGE/parameter_def.gms, message_ix/model/MESSAGE/scaling_investment_costs.gms
As explained in issue #652, this PR aims to adjust the calculation of levelized_costs, so that these are not only calculated when investment costs are parametrized for a technology, but also when variable costs *only* have been defined.
A Specific test cannot be written because it is not possible to retrieve the parameter "levelized_cost" from the scenario object.
~- [ ] Add or expand tests; coverage checks both ✅~
=> Correct levelized_cost calculation

RELEASE_NOTES.rst, doc/api.rst, message_ix/model/MESSAGE/data_load.gms, message_ix/model/MESSAGE/model_core.gms, message_ix/model/MESSAGE/parameter_def.gms, message_ix/model/MESSAGE/sets_maps_def.gms, message_ix/models.py, message_ix/tests/test_feature_storage.py, message_ix/tests/test_reporting.py, message_ix/tests/test_tutorials.py, message_ix/util/__init__.py
This PR addresses #632 by adding `mode` to the mapping set of storage technologies (`map_tec_storage`) and also to storage equations.
More details:
This change means re-initializing the existing set of `map_tec_storage` with new index sets. Based on the discussion in #631, this re-initializing happens automatically by modifications in the file `models.py`, only if the mapping set is empty. If the set is not empty, an exception is raised, telling the user that they need to update this set.
Moreover, this PR improves the documentation of storage section to reflect the above changes and more than that, adding required details for each equation.
- create a branch from the submitted PR; load an existing scenario (from Westeros, national or global models); clone a new scenario without carrying …
=> Enhancing storage equations by considering `mode` and `lvl_temporal`

doc/time.rst, message_ix/model/MESSAGE/parameter_def.gms
Closes #701 by including minor changes in the documentation.
- Read the diff and note that the CI checks all pass
- Build the documentation and look at the page(s) that changed
=> Fix inconsistencies in docs of special time slice value Year

doc/README.rst, doc/contrib/release.rst, doc/efficiency.rst, doc/time.rst
This PR simply writes `\text{xyz}` in Latex math mode in the docs where before it used to be `xyz`. This should improve [the time page](https://docs.messageix.org/en/stable/time.html) and [the efficiency page](https://docs.messageix.org/en/stable/efficiency.html).
- Build the documentation and look at the changed pages
=> Improve depiction of Latex text in docs

.github/workflows/pytest.yaml, message_ix/tests/test_core.py, message_ix/tests/test_feature_bound_activity_shares.py, message_ix/tests/test_feature_bound_emission.py, message_ix/tests/test_feature_capacity_factor.py, message_ix/tests/test_feature_duration_time.py, message_ix/tests/test_feature_storage.py, message_ix/tests/test_feature_temporal_level.py, message_ix/tests/test_soft_constraints.py, message_ix/tests/test_tutorials.py, message_ix/tests/tools/test_add_year.py, pyproject.toml
Some of the tutorial tests are "flaky": they occasionally fail on the GitHub Actions runners, e.g. [here](https://github.com/iiasa/message_ix/actions/runs/5030524087/jobs/9023255135). This necessitates daily work to restart the CI runs.
Per the [Pytest docs on flaky tests](https://docs.pytest.org/en/stable/explanation/flaky.html), this PR:
- Adds [`pytest-rerunfailures`](https://github.com/pytest-dev/pytest-rerunfailures) to the tests dependencies.
- Applies the "flaky" marker to these tutorial tests.
Also:
- Advertise Python 3.11 support in classifiers, and test against Python 3.11 on CI (parallel to iiasa/ixmp#481).
- Update deprecated usage in the test suite: mainly of `float(…)` to get a single value from a pandas.DataFrame; using `DataFrame.at[…]` or `.item()` instead.
Confirm at …
=> Address tests that are flaky on GHA

.github/workflows/conda.yaml
~Since we pinned the message-ix version to help the conda workflow pass, we need to keep this version number up-to-date.~
The above was true in principle, but did not solve our CI conda-forge test problems. As suggested in conda/conda/issues/12741, replacing the conda solver with the mamba solver did. This even allows us to remove the message_ix version pin entirely.
=> Use mamba solver instead of conda solver

INSTALL.rst
Closes #698 and #718. According to the notes I gathered during recent installation/CI runs, this PR 
* recommends the libmamba solver when installing via conda
* corrects the dependency arguments (or adds them) when using pip
* recommends adding the main repo as remote `upstream` and fetches the tags from there
- Build the documentation and look at the installation page.
Except for `macos-latest-py3.7` per iiasa/ixmp#484.
- ~Update release notes.~ Not applicable.
=> Update installation instructions

RELEASE_NOTES.rst, doc/conf.py, doc/references.bib, message_ix/model/MACRO/macro_core.gms, message_ix/model/MESSAGE/model_core.gms, message_ix/model/MESSAGE/model_solve.gms, message_ix/model/MESSAGE/parameter_def.gms, message_ix/model/MESSAGE/scaling_investment_costs.gms, message_ix/model/MESSAGE/sets_maps_def.gms
This PR puts all  strings with more than two characters in `\text{}`, which should help the depiction of long formulae in particular. Note that some single characters have seen the same fate, especially in `macro_core.gms`, because it would have appeared inconsistent to have some parameters in a table be in `\text{}` and not others if they represent the same thing thematically.
- Build the documentation and look at the 'Mathematical Specification' pages.
Except for `macos-latest-py3.7` per iiasa/ixmp#484.
=> Improve depiction of Latex in GAMS-created docs

INSTALL.rst
As pointed out by Marek, the link to GitHub in footnote 2 of the install instructions was broken. 
- Build the documentation, look at the installation page, try to follow the link in 'Anaconda -> Step 4 -> Footnote 2'
Except for `macos-latest-py3.7` per iiasa/ixmp#484.
=> Fix link in install instructions

pyproject.toml
This was missed in #719. It is required during the Sphinx docs build, in order for the `ixmp.utils.sphinx_linkcode_github` extension to identify the branch name to link, in both:
- RTD (example failed build [here](https://readthedocs.com/projects/iiasa-energy-program-message-ix/builds/1619490/)).
- The "pytest" CI workflow run on a schedule event (example failed job [here](https://github.com/iiasa/message_ix/actions/runs/5664864272/job/15348807463#step:13:23)).
This issue was/is not visible on the CI workflow job on the PR branch, because in that case the explicitly supplied head_ref is used: https://github.com/iiasa/message_ix/blob/4034d8c462bceef8b675ea84f0546bd60be93add/.github/workflows/pytest.yaml#L127-L131
The added dependency mirrors ixmp; in the ixmp CI the extension is working …
=> Add GitPython to "docs" optional deps

message_ix/tests/test_feature_bound_activity_shares.py, message_ix/tests/test_feature_price_emission.py, message_ix/tests/test_integration.py, message_ix/tests/test_legacy_version.py, message_ix/tests/test_macro.py, message_ix/tests/test_tutorials.py
Closes #731 by marking tests as flaky. Through discussion with @khaeru, we agreed that this is the best option for now; should the tests make more issues in the future, we can still identify their root cause.
- ~[ ] Add, expand, or update documentation.~ Nothing new added.
- ~[ ] Update release notes.~ Nothing public-facing added
=> Handling flaky tests

.readthedocs.yaml
As noted in #734, until we decide/invest enough time to enable the PDF builds for our docs (again), we should remove this version of the docs to keep the builds from failing.
I don't think we'll be able to build the PDF version from a PR build, we might be able to trigger a run manually on RTD for a branch build that builds epub and html, but no pdf. If not, we will only see this working after the merge, but the changes are small enough to understand they won't break anything.
- ~[ ] Add or expand tests; coverage checks both ✅~ ONly change docs config.
- ~[ ] Add, expand, or update documentation.~ Only change docs config.
- ~[ ] Update release notes.~ Only change docs config.
=> Disable PDF docs build

.github/dependabot.yml
This PR introduces a dependabot configuration file with the aim of automatically setting @khaeru and myself as assignees and reviewers for dependabot PRs.
I'm not entirely sure how to best test this config file. Can we point dependabot to this branch and wait for the next PR to pop up?
Apart from that, you can check that the file is following the official guidelines. It pieces together a few options, namely [assignees](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#assignees), [labels](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#labels), and [reviewers](https://docs.github.com/en/code-security/dependabot/dependabot-version-up …
=> Include dependabot configuration file

.github/dependabot.yml
This PR adapts the dependabot config file to reduce the number of PRs created by bumping versions. It does so in two ways:
1. [Group all dependencies together](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/customizing-dependency-updates#example-2) so that version updates will only be one PR
2. Decrease the [`schedule.interval`](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#scheduleinterval) to monthly
- ~[ ] Add or expand tests; coverage checks both ✅~ No functionality added.
- ~[ ] Add, expand, or update documentation.~ Nothing user-facing added.
- ~[ ] Update release notes.~ Nothing user-facing added.
=> Reduce number of dependabot PRs

message_ix/model/MESSAGE/model_core.gms
Since we won't be able to merge #723 in time, this PR adds a warning in the docs to where `PRICE_EMISSION` [is defined](https://docs.messageix.org/en/latest/model/MESSAGE/model_core.html#auxiliary-variables). This will allow us to postpone the fix for 3.8.1 in January.
I'm actually not sure: should we update the release notes?
- Check the documentation built by the RTD check below and look at MESSAGE core formulation -> Variable Definitions -> Auxiliary Variables.
- ~[ ] Add or expand tests; coverage checks both ✅~ Only docs
=> Add warning in docs about #723

message_ix/tests/test_macro.py
The recent dask update has brought to light an issue with one of our tests. `test_macro.py:test_config` wants to test, among others, that a missing column is causing a related error message. However, the test deletes three columns from the config and with the recent update, a different column from the expected one is picked up for the error message. This PR changes the test to delete only the one column from the config that we expect in the error message. 
- ~[ ] Add, expand, or update documentation.~ Just tests
- ~[ ] Update release notes.~ Just tests
=> Make test more specific to avoid error

RELEASE_NOTES.rst, pyproject.toml
As noted by @awais307, we should bump the minimum required version of genno to the one that introduces `genno.operator`. 
- ~[ ] Add or expand tests; coverage checks both ✅~ Just bumping dependency
- ~[ ] Add, expand, or update documentation.~ Just bumping dependency
- ~[ ] Update release notes.~ Just bumping dependency
=> Update minimum version of genno

.github/workflows/pytest.yaml
This PR removes the trigger for CI runs on pushed to main to avoid duplicate test runs. This avoids duplicate runs.
In order for this to work properly, we should make sure that
We might also want to 
All of which can be done via the [settings -> branches](https://github.com/iiasa/message_ix/settings/branch_protection_rules/17138230).
For now, we require the py3.12 and tutorial checks for macos, ubuntu, and windows to be successful.
- ~[ ] Add or expand tests; coverage checks both ✅~ Just changing how often tests are run.
- ~[ ] Add, expand, or update documentation.~ Just changing how often tests are run.
- ~[ ] Update release notes.~ Just changing how often tests are run.
=> Save minutes by avoiding duplicate test runs

RELEASE_NOTES.rst, message_ix/core.py, message_ix/tests/test_core.py
This PR improves the utility `Scenario.rename()` to resolve the bug identified in issue #601.
- Copy the unit test introduced in this PR (see the file `test_core.py` to your message_ix `main` branch. The test should fail with the existing code.
- Checkout to the branch of this PR, test should pass.
=> Improve `Scenario.rename()` to address #601

.github/workflows/pytest.yaml, .pre-commit-config.yaml, RELEASE_NOTES.rst, conftest.py, doc/api.rst, doc/contributing.rst, message_ix/cli.py, message_ix/report/operator.py, message_ix/testing/__init__.py, message_ix/testing/nightly.py, message_ix/tests/test_cli.py, message_ix/tests/test_core.py, message_ix/tests/test_feature_bound_activity_shares.py, message_ix/tests/test_feature_capacity_factor.py, message_ix/tests/test_feature_price_emission.py, message_ix/tests/test_feature_storage.py, message_ix/tests/test_feature_temporal_level.py, message_ix/tests/test_integration.py, message_ix/tests/test_legacy_version.py, message_ix/tests/test_macro.py, message_ix/tests/test_nightly.py, message_ix/tests/tools/test_add_year.py, message_ix/tools/add_year/__init__.py, message_ix/tools/add_year/cli.py, message_ix/util/__init__.py, pyproject.toml
This PR is to collect changes related to #776. As we notice tests "flaking", we can adjust them on this branch, and then merge once we feel we've addressed all observed flaky tests. The PR will thus remain open for a while until we're convinced we've reached that point.
- Job [1](https://github.com/iiasa/message_ix/actions/runs/7592300001/job/20681496117#step:9:439): `test_add_bound_activity_up_all_modes` fails with `assert np.isclose(300.0, 332.5)`.
+  where False = <function isclose at 0x105ed3f70>(300.0, 150.0)
+    where <function isclose at 0x105ed3f70> = np.isclose
On: macos-latest-py3.8
There was an execution error
For details, see the terminal output above, plus:
Listing   : …
=> Make tests robust & independent

INSTALL.rst
For https://github.com/iiasa/message-ix-models/pull/157, we want to link to the message_ix docs via intersphinx. That works fine for the most part, but we are missing labels for some subsections, so they are not yet reachable via intersphinx. This PR adds these labels.
- Check that the documentation is built without error.
- ~[ ] Add or expand tests; coverage checks both ✅~ Only adding docs labels
- ~[ ] Update release notes.~ Only adding docs labels
=> Introduce some additional labels in docs

.github/workflows/pytest.yaml, .pre-commit-config.yaml, doc/api.rst, doc/conf.py, doc/contrib/tutorial.rst, message_ix/core.py, message_ix/macro.py, message_ix/report/operator.py, message_ix/report/pyam.py, message_ix/testing/__init__.py, message_ix/tests/test_feature_duration_time.py, message_ix/tools/add_year/__init__.py, message_ix/util/__init__.py, pyproject.toml
- Adapt typing to genno 1.25.
- Defer import of pyam until needed; speeds up import of message_ix.
- Improve documentation cross-references using sphinx extensions provided by genno 1.26.
- Adjust code to pass type checks with pandas-stubs.
- Reduce max-complexity 15 → 13.
- ~Update release notes.~ No change in functionality.
=> Housekeeping for 2024-W13

.github/workflows/pytest.yaml
This PR is identical to https://github.com/iiasa/ixmp/pull/527, see there for an extensive background description.
- ~[ ] Add, expand, or update documentation.~
- ~[ ] Update doc/whatsnew.~
=> Use "macos-13" runner in "pytest" workflow

RELEASE_NOTES.rst, message_ix/macro.py, message_ix/tools/add_year/__init__.py
Closes #804.
This PR temporarily enables the pandas Copy-on-Write behaviour that will become standard with pandas 3.0. With this, I ran all tests locally to study the warnings we would get from this: only two files were affected, `add_year/__init__` and `macro`. Then, I fixed all of these warnings [as suggested in the migration guide](https://pandas.pydata.org/docs/user_guide/copy_on_write.html#copy-on-write), so we might be good with this repo (and all underlying ixmp functions called from the test suite here) :)
- Study CI output to see if any pandas Warnings wrt CoW came up that were skipped locally.
- Fix new Warnings (if any).
- Remove the `TEMPORARY` commit to avoid enabling pandas CoW for all users already.
- ~[ ] Add or expand …
=> Ensure compatibility with pandas CoW

.github/workflows/nightly.yaml, .github/workflows/pytest.yaml
This PR updates the "pytest" CI workflow to address two causes of failures:
- With NumPy 2.0.0 we run into unionai-oss/pandera#1685, which is a dependency via `message_ix.report` → `pyam-iamc` → `ixmp4`. We apply the mitigation discussed at khaeru/genno#140.
- ts-graphviz/setup-graphviz#630. This mirrors changes made in iiasa/ixmp#535.
Both of these are temporary work-arounds, are marked accordingly, and should be removed when the respective upstream packages are fixed.
=> Adjust CI for Numpy 2.0, Graphviz

.github/workflows/nightly.yaml, .github/workflows/pytest.yaml
https://github.com/iiasa/ixmp/pull/532 deleted some libraries that were used to run GAMS, which should now be read directly from a GAMS subdirectory. This PR adjusts the version of GAMS used in CI to check if this newer version enables finding the libraries.
- ~[ ] Add or expand tests; coverage checks both ✅~ Just internal CI.
- ~[ ] Add, expand, or update documentation.~ Just internal CI.
- ~[ ] Update release notes.~ Just internal CI.
=> Bump GAMS version in CI workflows to adjust for ixmp changes

doc/conf.py
Starting on October 7, [RTD will switch to RTD Addons](https://about.readthedocs.com/blog/2024/07/addons-by-default/) for sphinx projects, too. They have identified that this is going to impact message_ix and suggest to change our configuration file in almost exactly the way this PR does. I have [enabled Addons temporarily on RTD](https://app.readthedocs.com/dashboard/iiasa-energy-program-message-ix/addons/edit/) and intend to use this PR to make any adjustments necessary to keep our docs building as expected. 
- Look at the docs built from this PR and confirm they are what we want/expect.
- ~[ ] Add or expand tests; coverage checks both ✅~ Just docs-related.
- ~[ ] Update release notes.~ Just docs-related.
=> Adjust to RTD's upcoming addon changes

.github/CONTRIBUTING.md, .github/SECURITY.md, CODE_OF_CONDUCT.md, GOVERNANCE.md, README.md, RELEASE_NOTES.rst, SUPPORT.md, doc/index.rst
Today, I stumbled upon [GitHub's guidelines for establishing a healthy community](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions). This PR includes various suggested files to improve the experience of working with `message_ix`.
Apart from these files, GitHub also suggests to turn on various security features that we had not enabled, so I did that as well. That is why we are seeing new CI checks: GitHub checks if any `secrets` haven been accidentally included. We also now accept people [directly reporting vulnerabilities in our code](https://github.com/iiasa/message_ix/security/advisories/new) in private.
One feature I'm not sure is working even though I did enable it is that the repository admins accept content reports (please see …
=> Improve GitHub community standards

RELEASE_NOTES.rst, doc/install-adv.rst, message_ix/cli.py, message_ix/tests/conftest.py, message_ix/tests/test_cli.py, message_ix/tests/test_core.py, message_ix/tests/test_feature_bound_activity_shares.py, message_ix/tests/test_feature_storage.py, message_ix/tests/test_macro.py, message_ix/tests/test_report.py, message_ix/tests/test_util.py, message_ix/tests/tools/test_add_year.py, message_ix/util/__init__.py
Closes #797.
This is a follow-up PR to #784 with the aim of bringing even more test stability into our CI suite.
For the moment (at least while it's free), this PR experiments with [codecov's new flaky-test-detection feature](https://about.codecov.io/blog/find-failing-and-flaky-tests-with-codecov-test-analytics/).
- Read the PR comments and ensure the reasoning makes sense.
- ~[ ] Add, expand, or update documentation.~ Just CI.
=> Make more tests robust and independent

.pre-commit-config.yaml, message_ix/tools/add_year/__init__.py, pyproject.toml, tutorial/westeros/westeros_report.ipynb
Our CI failed today because of the [release of mypy 1.12](https://mypy.readthedocs.io/en/stable/changelog.html).
This PR collects changes to adjust. It also includes a suggested change, namely to activate `local_partial_type = true` since this is planned to become the default with mypy 2.0. However, this setting does not seem to affect this repository too much :)
This PR is likely a prerequisite for other PRs as they won't be able to clear the code quality check before being rebased on this one.
- ~[ ] Add or expand tests; coverage checks both ✅~ Just adjusting to dependency.
- ~[ ] Add, expand, or update documentation.~ Just adjusting to dependency.
- ~[ ] Update release notes.~ Just adjusting to dependency.
=> Support mypy 1.12

.github/workflows/nightly.yaml, .github/workflows/pytest.yaml
This PR tries to resolve the CI test failures by not using version 2024.11.0 of dask, which is causing [issues with genno](https://github.com/khaeru/genno/issues/149). 
The most preferable solution would be to adapt genno to this dask version, but it is unclear how much effort this would be and how long this would take. So for now, I'm simply imposing that we don't use that particular version (note: 2024.11.1 would be allowed, hoping that this might resolve the incompatibilities).
If this workaround is successful and we agree we want to employ it for now, we should also adopt it in the nightly workflow.
- ~[ ] Add, expand, or update documentation.~ Just CI.
- ~[ ] Update release notes.~ Just CI.
=> Replace resolved numpy workaround with dask workaround

.github/workflows/nightly.yaml, .github/workflows/pytest.yaml, INSTALL.rst, RELEASE_NOTES.rst, doc/install-adv.rst, message_ix/__init__.py, message_ix/core.py, message_ix/macro.py, message_ix/models.py, message_ix/report/__init__.py, message_ix/report/operator.py, message_ix/report/pyam.py, message_ix/testing/__init__.py, message_ix/tests/report/test_operator.py, message_ix/tests/test_feature_duration_time.py, message_ix/tests/test_feature_vintage_and_active_years.py, message_ix/tests/test_nightly.py, message_ix/tests/test_tutorials.py, message_ix/tools/add_year/__init__.py, message_ix/tools/lp_diag/__init__.py, message_ix/tools/lp_diag/cli.py, pyproject.toml
As suggested by @khaeru in #880, we should drop support for the now outdated version 3.8 of Python and add support for the new 3.13. This PR does just that.
Please also see the analogous https://github.com/iiasa/ixmp/pull/544, which details some issues that need to be closed upstream before we can support 3.13.
=> Update Python support for 3.13

.github/workflows/nightly.yaml, message_ix/tests/test_nightly.py
Similar to https://github.com/iiasa/message-ix-models/pull/250#pullrequestreview-2450593364, I'm hoping today's nightly CI test failure also just arises from an incompatibility of using an older GAMS version but a newer GAMS license for this kind of run. This PR thus bumps the GAMS version in the nightly workflow and temporarily enables them to make sure the fix works.
- ~[ ] Add, expand, or update documentation. ~ Just CI.
- ~[ ] Update release notes. ~ Just CI.
=> Bump GAMS version in nightly CI worklow

.github/workflows/pytest.yaml, .github/workflows/receive.yaml
This PR implements the approach recommended by [this article](https://securitylab.github.com/resources/github-actions-preventing-pwn-requests/) from Github's ‘Security Lab’ to allow the usage of secrets on PRs from forks of the `message_ix` repository.
- Add a "receive" CI workflow.
- Run on all PRs into `main`.
- Fail if (a) the PR is from a fork and (b) it does not have a certain label, currently "safe to test".
- Adjust the "pytest" CI workflow:
- Add a `workflow_run:` event trigger. Invoke this trigger every time the "receive" workflow completes (success or failure).
- Skip the main `pytest` and `tutorials` jobs if the "receive" workflow failed.
- Invoke actions/checkout with the right options to use the fork PR branch.
With this merged, it would be up to some user with ‘write’ …
=> Allow moderated secrets usage on PRs from forks

.github/workflows/pytest.yaml, .pre-commit-config.yaml, message_ix/tests/test_report.py
We're seeing the same error in our CI again as we did previously when GitHub runner-images first changed `ubuntu-latest` to Ubuntu 24.04. They are rolling out the same change again now. However, we have adopted Python 3.13 in the meantime and in the ixmp test suite, this seems to work, while Python 3.12 produces the same error with Ubuntu 24.04. 3.11 works with that image, too, so the error might be specific to Python 3.12. Thus, this PR bumps the Python version we use for the tutorial tests in hopes of enabling them to run again on `ubuntu-latest`.
If this works, we might be able to adjust the ixmp test suite to only use Ubuntu 22.04 with Python 3.12.
See https://github.com/IRkernel/IRkernel/issues/747 and https://github.com/r-lib/actions/issues/932 for the issues I opened about this …
=> Bump Python version for tutorials

.github/workflows/pytest.yaml
As discovered in https://github.com/iiasa/message_ix/pull/904#issuecomment-2577300711, it seems we need to bring to `main` a version of the "Pytest" workflow that doesn't run on all PRs to `main` and that uses the correct data for the checkout action when being dispatched from the "Receive PR" workflow. This PR cherry-picks the two commits from #904 that achieve this. 
- ~Read the diff and note that the CI checks all pass.~
- Note that this PR should trigger the "Pytest" workflow only once, after successfully completing the "Receive PR" workflow.
- ~Continuous integration checks all ✅~ These fail because of the underlying issue. Merging the changes will address the issue.
- ~[ ] Add, expand, or update documentation.~ Just CI.
- ~[ ] Update release notes.~ Just CI.
=> Fix workflow runs from forks

.github/workflows/pytest.yaml, .pre-commit-config.yaml
#909 introduced invalid GitHub Actions syntax 🤦🏾‍♂️. This PR:
- Fixes the error.
- Adds pre-commit configuration to check that the workflow files (a) are valid YAML and (b) conform to GitHub's published schemas.
Read the diff.
- ~Continuous integration checks all ✅~ As with #909, the required checks from the "pytest" workflow will not run; this time because of the syntax error.
- ~Add or expand tests; coverage checks both ✅~
- ~Add, expand, or update documentation.~ N/A, CI changes only
=> Validate CI workflows

.github/workflows/pytest.yaml, .pre-commit-config.yaml, README.md, RELEASE_NOTES.rst, doc/conf.py, doc/index.rst, message_ix/model/MESSAGE-MACRO_run.gms, message_ix/model/MESSAGE_master.gms, message_ix/model/MESSAGE_run.gms, message_ix/model/includes/copyright.gms, pyproject.toml
Parallel to iiasa/ixmp#555, plus:
- Adjust 'tutorial' jobs in 'pytest' CLI workflow to align with #909, #910.
- Bump copyright year.
- …items below.
- View the [revised docs](https://iiasa-energy-program-message-ix--911.com.readthedocs.build/en/911/), in particular:
- Mention of the newsletter on the index page.
- Organization of the index page and navigation pane.
=> Clean up CI & miscellaneous updates for 3.10

.github/workflows/pytest.yaml, message_ix/models.py, message_ix/tests/test_core.py, message_ix/tests/test_models.py, message_ix/tools/lp_diag/__init__.py, message_ix/util/sphinx_gams.py, tutorial/westeros/westeros_historical_new_capacity.ipynb
#911 used double-quotes erroneously. This was not picked up by the actions-validator pre-commit hook, unfortunately. This causes errors like [this](https://github.com/iiasa/message_ix/actions/runs/12916949865).
Also:
- Check out the correct commit even on events other than pull_request_target.
- Apply ruff format to additional files.
Read the diff.
- ~Continuous integration checks all ✅~ Checks will not run because of the error.
- ~Add or expand tests; coverage checks both ✅~ ditto
- ~Add, expand, or update documentation.~ N/A; CI and formatting changes only
- ~Update release notes.~ ditto
=> Fix quoting in "pytest" GitHub Actions workflow

RELEASE_NOTES.rst, message_ix/model/MESSAGE/data_load.gms, message_ix/model/MESSAGE/model_core.gms, message_ix/model/MESSAGE/model_solve.gms, message_ix/models.py, message_ix/tests/test_feature_price_emission.py, message_ix/tests/test_report.py, message_ix/tests/test_tutorials.py, tutorial/westeros/westeros_emissions_taxes.ipynb
In preparation of the 3.10 release, @khaeru and I noticed that the [original PR](https://github.com/iiasa/message_ix/pull/726) to fix `PRICE_EMISSION` (address #723) has become a little cluttered with discussions of how to create a proper test for the calculation update. Meanwhile, @volker-krey suggested that we should just bring the fix to `main` and open a follow-up issue to create the test later. Thus, this PR adds all changes from #726 that seem to be necessary to fix the calculation and make the tests pass as they are. 
>[!CAUTION]
>The error with the current calculation of `PRICE_EMISSION` went undetected so long because our tests were not stringent enough. Hence our initial insistence that #726 contain the exact kind of test to prevent the issue from coming up again. Such a test is …
=> Fix `PRICE_EMISSION` definition

doc/conf.py, doc/macro.rst
- Remove intersphinx config for unmaintained iiasa/message_doc.
- Link to location within iiasa/message-ix-models docs.
- View the diff.
- View the MACRO page in the RTD preview build.
- Ensure the edited intersphinx link goes to the right place.
=> Adjust links to MESSAGEix-GLOBIOM docs

.github/workflows/conda.yaml
Unfortunately, it looks like the release v3.10.0 of ixmp broke the "install from conda forge" CI here, but only the tests running on windows machines. 
Comparing ixmp 3.9 to 3.10, we see that the way we collect the GAMS information has changed. Not dramatically and on macos, everything still works fine, which makes me think I'm still missing something here. However, looking at the backtrace, we see this bit:
```python
File "D:\a\_actions\iiasa\actions\main\setup-conda\Anaconda3\envs\testenv\Lib\site-packages\ixmp\cli.py", line 59, in main
mp = ixmp.Platform(name=platform)
File "D:\a\_actions\iiasa\actions\main\setup-conda\Anaconda3\envs\testenv\Lib\site-packages\ixmp\core\platform.py", line 95, in __init__
self._backend = backend_class(**kwargs)
~~~~~~~~~~~~~^^^^^^^^^^
File …
```
=> Fix "install from conda forge" CI after ixmp release v3.10.0

.github/workflows/conda.yaml
Unfortunately, our release 3.10.0 broke our own "install from conda forge" CI _again_. This PR will eventually fix that.
We see this error upon test collection in the CI run:
```python
ImportError while importing test module 'D:\a\_actions\iiasa\actions\main\setup-conda\Anaconda3\envs\testenv\Lib\site-packages\message_ix\tests\tools\test_sankey.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
D:\a\_actions\iiasa\actions\main\setup-conda\Anaconda3\envs\testenv\Lib\site-packages\message_ix\tools\sankey.py:5: in <module>
from pyam.str import get_variable_components
E   ModuleNotFoundError: No module named 'pyam.str'
During handling of the above exception, another exception occurred:
D:\a\_actions\iiasa\actions\main\setup-conda\Anaconda3\envs\testenv\Lib\impo …
```
=> Fix "install from conda forge" CI  broken by release 3.10.0

message_ix/tools/add_year/__init__.py
v2.2.3.250308 of pandas-stubs broke our Code Quality CI check with an error about indexing a `pandas.DataFrame`. This PR makes the check pass again.
The error we received was
```python
message_ix/tools/add_year/__init__.py:84: error: Invalid index type "list[str]" for "_LocIndexerFrame[DataFrame]"; expected type "slice[Any, Any, Any] | ndarray[Any, dtype[integer[Any]]] | Index[Any] | list[int] | Series[int] | <6 more items>"  [index]
```
and the code in question was
```python
def mask_df(df: pd.DataFrame, index: str, count: int, value) -> None:
"""Create a mask for removing extra values from *df*."""
df.loc[
index,
df.columns
> (df.loc[[index]].notnull().cumsum(axis=1) == count).idxmax(axis=1).values[0],
] = value
```
I think I put in the type hint of `index: str` as I understood it, but …
=> Fix Code Quality test after pandas-stubs v2.2.3.250308

RELEASE_NOTES.rst, doc/conf.py, message_ix/model/MACRO/macro_solve.gms, message_ix/model/MESSAGE/parameter_def.gms
This PR ~implements a fix for a bug in the `duration_period_sum` set documented in #925.~
- Adds documentation of duration_period_sum to clarify its meaning/interpretation/use.
- Adds in-line comments where it is used in MACRO/model_solve.gms.
See #925 and the discussion below for more details.
- Look at the added "What's new" entry and the docs that it links to.
- Read the diff, especially the added inline comments in the GAMS code.
=> Document duration_period_sum and its use

RELEASE_NOTES.rst, message_ix/model/MESSAGE/data_load.gms
As observed by both @ywpratama and I (in iiasa/message_data#605), from commit iiasa/message_ix@76eaa511c7d772bc3584bbbe5d64ea1fa424395a the GAMS code is very slow to execute for larger models. The difference is not noticeable within the message_ix test suite, and thus in #930, but becomes evident in larger (e.g. MESSAGEix-GLOBIOM) scenarios. For detailed symptoms see [Slack](https://iiasa-ece.slack.com/archives/CD0GBHHA4/p1745402028391619).
This one commit makes the following two changes to the implementation:
- Use SUM() instead of SOR().
- Use $-condition on left-hand side, instead of computing YES/NO on the RHS.
Although these have identical effects, the code executes much faster. It's not clear why: I searched for information about the performance of GAMS for these different …
=> Adjust GAMS expression for type_tec_{share,total}

RELEASE_NOTES.rst, doc/api.rst, message_ix/model/MACRO/macro_solve.gms, message_ix/model/MACRO/setup.gms, message_ix/model/MACRO_run.gms, message_ix/model/MESSAGE-MACRO_run.gms, message_ix/model/MESSAGE_master.gms, message_ix/models.py, message_ix/tests/test_macro.py
This PR introduces the option to solve for all regions concurrently in MACRO. A parameter (''solve_param'') has been added to ''MESSAGE-MACRO'' to control the solving mechanism for MACRO. Setting ''solve_param'' to 1 (the default value) triggers sequential solving across regions, whereas setting it to 2 enables concurrent solving.
An if statement has also been introduced in ''macro_solve'' that dictates whether sequential or concurrent solving is applied in MACRO, based on the value of the ''solve_param'' parameter defined in ''MESSAGE-MACRO_run''. The default solving is sequential (''solve_param''=1), so if the user doesn't update the solving mechanism, MACRO is solved as it used to be. In terms of efficiency, the concurrent solving is subtly more efficient. 
For the concurrent solving …
=> Add an option to solve MACRO concurrently for all regions

message_ix/macro.py
pandas-stubs version 2.3.0 was released 2025-07-02 (lagging about a month behind pandas itself). This caused mypy errors [here](https://github.com/iiasa/message_ix/actions/runs/16042038021/job/45265360347#step:5:44):
```
message_ix/macro.py:283: error: No overload variant of "apply" of "DataFrameGroupBy" matches argument types "Callable[[DataFrame], float]", "dict[str, bool]"  [call-overload]
message_ix/macro.py:283: note: Possible overload variants:
message_ix/macro.py:283: note:     def [P`17067] apply(self, DFCallable1[P], /, *args: P.args, **kwargs: P.kwargs) -> Series[Any]
message_ix/macro.py:283: note:     def [P`17068] apply(self, DFCallable2[P], /, *args: P.args, **kwargs: P.kwargs) -> DataFrame
message_ix/macro.py:283: note:     def [P`17069] apply(self, DFCallable3[P], /, *args: …
```
=> Remove Python 3.8 compat in .macro.extrapolate()

.github/workflows/pytest.yaml, RELEASE_NOTES.rst, doc/conf.py, doc/install-adv.rst
Parallel to iiasa/ixmp#586, use a version of Java compatible with JPype1 v1.6.0. This version of JPype was released 2025-07-07 and triggered failures of the `windows-latest-py3.1[123]` and `windows-latest tutorials` scheduled testing jobs, for instance [here](https://github.com/iiasa/message_ix/actions/runs/16134446053).
- I initially tried the settings:
```yaml
distribution: 'temurin'
java-version: 11
```
- This caused ([here](https://github.com/iiasa/message_ix/actions/runs/16253568336/job/45887494779?pr=962)) all the Windows jobs to fail with `java.lang.OutOfMemoryError: Java heap space`.
- I imagine this is due to different memory usage characteristics of (a) the underlying Java version, (b) JPype, (c) ixmp_source, or (d) some interaction of the first three, such that more memory is …
=> Use Java 21 on Windows GHA runners
