iiasa/message_ix

- AUTHORS.md
...updated ixmp to give user otpion to allocating more heap space.
> Updated submodule ixmp

- README.md
- tutorial/Austrian_energy_system/austria.ipynb
@benham2015 does this align with your experiences?
> add notes on how to start tutorials

- .travis.yml
- RELEASE_NOTES.md
> add travis support

- RELEASE_NOTES.md
- message_ix/core.py
- tests/test_core.py
> rename now optionally removes

- RELEASE_NOTES.md
- message_ix/core.py
> bugfix for solving macro

- message_ix/core.py
- tests/test_core.py
> rename: only checkout and commit if already checked out

- tests/test_tutorials.py
- tutorial/westeros/westeros_baseline.ipynb
> fix py2 westeros

- .travis.yml
> testing multi py on travis

- README.md
> Updating the link for downloading conda

- setup.py
needed for packaging of new release
> find version in setup.py the same way as in __init__.py

- RELEASE_NOTES.md
- message_ix/core.py
- tests/test_feature_addon.py
- tests/test_feature_bounds_shares.py
- tests/test_macro.py
testing out a possible ci issues with #131
> update clone kwarg from scen to scenario

- RELEASE_NOTES.md
- tests/test_bound_emission.py
> Test for bound_emission (either cumulative or per model year)

- tests/test_reporting.py
Updating message tests with new ixmp reporting
depends on iiasa/ixmp#147
> message tests now pass with updated ixmp.testing

- .travis.yml
- appveyor.yml
- ci/travis-install.sh
- message_ix/reporting/__init__.py
- setup.py
No-op to check if CI is failing on current master
> Use bleeding-edge pyam in CI + reporting hotfix

- message_ix/reporting/__init__.py
- tests/test_reporting.py
Adds more reporting capability per (private repo): https://github.com/iiasa/message_data/wiki/Reporting
> Adjust standard set of reported products

- doc/requirements.txt
Closes #233.
This will be complete when the reporting page in https://message.iiasa.ac.at/en/issue-233/ correctly includes the documentation for message_ix.Reporter.
> Use bleeding-edge pyam in RTD build

- INSTALL.rst
- doc/source/conf.py
More direct link to ixmp installation instructions.
> More direct link to ixmp installation instructions.

- message_ix/model/MESSAGE/parameter_def.gms
PR #273 was merged accidentally; this PR reverts it.
The changes of PR #273 related to documentation is reverted.  This version goes back to the commit `8bf4ecf7b2721b9c8b0ba3610dc88ac5cad141c3` by @khaeru. This is done to ensure that the previously merged PR #273 successfully passes all the CI tests.
> #273 was merged accidentally; this PR reverts it.

- ci/codecov.yml
- tests/test_models.py
This PR tweaks the Codecov configuration.
> Adjust Codecov configuration

- INSTALL.rst
- doc/source/reporting.rst
> Mention minimum GAMS for MACRO in INSTALL.rst

- doc/source/reporting.rst
- message_ix/reporting/computations.py
Adjust to reorganization of ixmp.reporting in iiasa/ixmp#267.
> Adjust ixmp.reporting imports

- .travis.yml
- doc/source/reporting.rst
- message_ix/reporting/__init__.py
- setup.cfg
`Reporter.from_scenario` is simplified using the code in iiiasa/ixmp#312.
- ~Wait for iiasa/ixmp#312 to merge.~
> Reporting improvements for 2020-W16

- ci/conda-requirements.txt
Parallel to iiasa/ixmp#318. See iiasa/ixmp#279.
> Exclude JPype1 0.7.3

- RELEASE_NOTES.rst
- doc/source/api.rst
- message_ix/core.py
- message_ix/model/MESSAGE-MACRO_run.gms
- message_ix/models.py
- message_ix/tests/test_models.py
Closes #342.
- Check that the parameters can be changed from run to run through calls like `Scenario.solve(..., max_iteration=1)`.
> Pass MESSAGE-MACRO convergence parameters through API

- .gitignore
- message_ix/tests/test_cli.py
> Add .eggs to .gitignore

- README.md
- RELEASE_NOTES.rst
- rmessageix/DESCRIPTION
- setup.cfg
- tutorial/README.rst
Per the [release procedure](https://github.com/iiasa/message_ix/wiki/Release-procedure):
> Prepare release 3.1.0

- tutorial/westeros/westeros_report.ipynb
> Copyedit westeros_report tutorial per 2020-09 workshop feedback

- NOTICE.rst
- README.md
- RELEASE_NOTES.rst
- doc/source/framework.rst
Closes #398.
View the changes; view the README as rendered by GitHub.
- ~Add or expand tests.~ No code changes.
> Add Zenodo badge & citation instructions

- .github/workflows/lint.yml
- .github/workflows/nightly.yml
- .github/workflows/pytest.yml
Closes #413.
Note that the CI checks all pass.
- ~Add or expand tests.~ N/A; CI changes only.
> Adjust CI workflow for Python 3.9

- RELEASE_NOTES.rst
- doc/contrib/release.rst
- message_ix/model/MESSAGE/model_core.gms
- message_ix/model/MESSAGE/parameter_def.gms
This PR captures some points given orally in today's MESSAGEix meeting about the parameters related to dynamic constraints, related to discussion of https://github.com/iiasa/message-ix-models/pull/13#issuecomment-814254659.
Also:
- Add a ToC to the model core formulation page.
- Add a cross reference from the dynamic constraint equations to the related parameters.
No review: docs changes only.
> Expand docs of dynamic constraint parameters

- RELEASE_NOTES.rst
- tutorial/README.rst
- tutorial/westeros/westeros_flexible_generation.ipynb
This PR updates the tutorial on adding flexible generation constraints.
This is the second of three tutorials on various features surrounding the renewables.
Run tutorial
Read through tutorials and see if the explanantions are understandable 
~ - [ ] Tests added. Tutorial added~
~ - [ ] Documentation added. already included ~
> Update Westeros tutorial: flexible generation

- INSTALL.rst
This PR updates the documentation "Common issues" section by the _No module named 'pyam'_ error message and solves issue [#237](https://github.com/iiasa/message_ix/issues/237)
- Build the documentation and look at the installation page.
> Update documentation "Common issues"

- .github/workflows/conda.yaml
This PR extends the CI checks for conda. Merging this PR will close issue #386.
> Extend CI checks for conda

- message_ix/macro.py
- message_ix/testing/__init__.py
- message_ix/tests/test_cli.py
This PR adjust files to the new black release. 
Closes #555. 
> Adjust files to new black release

- message_ix/reporting/__init__.py
This is a minor change to remove a deprecated function argument. A parallel change was made in iiasa/ixmp#444.
Run a specific code snippet or command and check the output.
- ~Add, expand, or update documentation.~ N/A, no change to user-facing behaviour
- ~Update release notes.~ N/A
> Adjust .Reporter.get_tasks for genno 1.11

- .github/workflows/pytest.yaml
- message_ix/tests/test_tutorials.py
- ~Add, expand, or update documentation.~ N/A, CI changes only
> Run "pytest" CI workflow daily on a schedule trigger

- .github/workflows/conda.yaml
- .github/workflows/lint.yaml
- .github/workflows/nightly.yaml
- .github/workflows/publish.yaml
- .github/workflows/pytest.yaml
- ~Add, expand, or update documentation.~ N/A
> Miscellaneous CI updates for 2022-W44

- .github/workflows/lint.yaml
- .github/workflows/publish.yaml
- message_ix/core.py
- message_ix/reporting/pyam.py
Parallel to iiasa/ixmp#466; see description there.
- ~Add, expand, or update documentation.~ N/A; CI changes only
> Use reusable workflows for "lint" and "publish"

- .github/workflows/pytest.yaml
- message_ix/util/sphinx_gams.py
See iiasa/ixmp#468
- ~Add, expand, or update documentation.~ N/A; CI changes only.
> Update ts-graphviz/setup-graphviz v1.1 → v1.2.0

- CITATION.cff
Fix Francesco Lovat's name and add his orcid.
No review, simple typo fix.
- ~[ ] Add or expand tests; coverage checks both~ Just a typo fix.
- ~[ ] Add, expand, or update documentation.~ Just a typo fix.
- ~[ ] Update release notes.~ Just a typo fix.
> Fix typo in citation file

- CITATION.cff
- doc/contrib/release.rst
Closes #786 by 
- introducing the `doi`, `version`, and `date-released` keys
- introducing quotation marks for [strings containing white spaces and other special signs](https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md)
- updating all quotation marks from `'` to the recommended `"`
- updating the list of authors
- updating the release procedure to update the new keys
- Build the documentation and look at the release procedure page.
- If you know how to see what the new automatic citations by GitHub will look like, please check they are looking as intended.
- ~[ ] Add or expand tests; coverage checks both ✅~ Only updating docs
- ~[ ] Update release notes.~ Only updating docs
> Update citation file

- CITATION.cff
- RELEASE_NOTES.rst
- doc/contrib/release.rst
- pyproject.toml
Releases v3.9.0 :)
- In particular, check that the ['publish' workflow passes](https://github.com/iiasa/message_ix/actions/runs/9366890757/job/25785379351?pr=849).
- Check that the rc version is available [here](https://pypi.org/project/message-ix/3.9.0rc1/).
- ~[ ] Add or expand tests; coverage checks both ✅~ Just releasing.
- ~[ ] Add, expand, or update documentation.~ Just releasing.
> Release v3.9.0

- message_ix/model/MESSAGE/data_load.gms
- message_ix/model/MESSAGE/model_learningeos.gms
- message_ix/model/MESSAGE/model_setup.gms
- message_ix/model/MESSAGE/model_solve.gms
- message_ix/model/MESSAGE/parameter_def.gms
- message_ix/model/MESSAGE/sets_maps_def.gms
- message_ix/model/MESSAGE_master.gms
- message_ix/models.py
- message_ix/tools/add_cdr/__init__.py
This PR moves Learning and CDR modules from private repository to CDR project branch, based on the ssp_dev branch,
No review at the moment. Tests will be developed and review will be required when the modules are planned to be merged to main
> Migrating learning and CDR modules to project CDR branch
